package Day_37_Exception_Part2.throwException;

public class ReTrowingRunTimeException {
    public static void main(String[] args) {
        throw new RuntimeException("My custom message");
    }
}
