package Day_37_Exception_Part2;

public class _01_TryCatchFinally {
    public static void main(String[] args) {
        try {

        }catch (Exception e){

        }finally{

        }

    }
}
